### ISSUE TITLE
Bug? Custom Slices Input Not Working

### ISSUE THREAD

**Issue by SimonasLetukas** [shenanigans-be/miltydraft#14]
Hello, not sure if this is intended or I'm just doing something wrong -- hopefully it's the latter. :) 

Steps taken:
1. Copied slices from generated draft -> config. 
![image](https://github.com/shenanigans-be/miltydraft/assets/4127189/d2bad1a0-ba70-40e4-884e-8d8ab412f20a)
2. Pasted them to custom slices to generate a new draft.
![image](https://github.com/shenanigans-be/miltydraft/assets/4127189/0c9980f9-aa46-44a9-a86d-2a59c777adf4)
3. New draft was generated with no slices.
![image](https://github.com/shenanigans-be/miltydraft/assets/4127189/62a670ec-eed9-4b2c-a81c-946af7509149)

Live draft: https://milty.shenanigans.be/d/6484cce63979f
Input: 
```
61,40,76,43,70
34,77,60,49,30
41,37,44,25,38
65,50,67,22,35
71,39,72,63,46
48,26,29,21,68
80,69,78,31,19
```

Tried on Firefox and Edge. Also tried adding spaces after commas, to have the same format as shown in the help text. Then tried different generation options and different inputs, but couldn't get it to render the slices...

**Comment by shenanigans-be** [comment]
Hi @SimonasLetukas. 
Thank you so much for reaching out! 

It's not you, it's me 😅 Turns out that I broke the custom-slice-stuff a couple days ago when I added the regeneration functionality. It's fixed now! 
The good news is: If you ran into this in a real draft you can "regenerate" the slices and it'll just fix the broken data.
