### ISSUE TITLE
Bug: Custom Selection of Factions

### ISSUE THREAD

**Issue by SimonasLetukas** [shenanigans-be/miltydraft#15]
Hi, I think I have another one for you, apologies :D

Demo:
https://milty.shenanigans.be/d/6485710c60996

I selected these factions: sardakk, letnev, hacan, sol, ghosts, naalu, nekro, winnu, xxcha, argent, empyrean, nomad + 2 random factions (homebrew ones not enabled)
What I got in the draft: sardakk, letnev, hacan, sol, ghosts, naalu, nekro, winnu, xxcha, argent, empyrean, nomad + mentak, florzen profiteers (!).

Seems like the homebrew factions get added to fill up the draft even when the option is disabled.

**Comment by shenanigans-be** [comment]
Hi @SimonasLetukas. Thanks for reaching out (again!) 😄

This is.. not exactly a bug, but a known issue that's addressed in the explanation of the Custom Factions: 

> Note: once you start fiddling with this, the above options to include/exclude PoK or Keleres will be ignored.

(The reasoning behind this is that the checkmarks are for broad-strokes config and if you're selecting custom factions anyway you know exactly which ones you want to include)

That being said: I should probably make it so that you can only select custom factions if the relevant checkboxes are on instead of half-assing it and making people responsible for reading all the fine print...

**Comment by shenanigans-be** [comment]
Fixed it immediately with https://github.com/shenanigans-be/miltydraft/commit/d8bfa14fed54178fbff0912b8f516843a6363959 cause the bad usability was bothering me.
