### ISSUE TITLE
Update draft picks without refreshing

### ISSUE THREAD

**Issue by dizbpg** [shenanigans-be/miltydraft#21]
- Currently in order to see any draft picks that were made after you loaded the draft page you need to manually refresh.

- It would be convenient for the information to updated automatically without need for refreshing.

**Comment by dizbpg** [comment]
If this suggestion is accepted, I would like to undertake it myself.

**Comment by shenanigans-be** [comment]
Hi @dizbpg 

This has been requested before, so I wouldn't mind seeing it implemented. The only caviat I'd suggest is to not just re-download the data on a timed interval, but instead listen for a window focus event or something and then check how long it's been since the data was refreshed. If people are going to leave this draft open for a couple of days (which is what I do usually) I would like to avoid the bandwidth of 100000 requests per user.

**Comment by shenanigans-be** [comment]
Based on @Keksike 's [PR](https://github.com/shenanigans-be/miltydraft/pull/28) ( I implemented an automatic refresh when the visitor's tab becomes active. I feel like this is a decent compromise that doesn't put too much load on the server.
